### ISSUE TITLE
Mantine witn Nextjs

### ISSUE THREAD

**Issue by JohannesMerkt** [cohstats/coh3-stats#1]
I am currently working with mantine and nextjs in another project. This is where i had to realize that nextjs SSR with mantine there is a managed starter template https://github.com/mantinedev/mantine-next-template . 

Since there is some complex setup needed to make mantine and nextjs work together I would suggest starting with that template.

also really nice in the template is the storybook that is already set up for you. Which is very usefull when designing components

**Comment by petrvecera** [comment]
YEah I am aware of that template. I didn't like it when I checked the package.json it has so many things ... :D 

It's true that I didn't try the SSR , will try if it works with mantine with the setup I have right now. 

<img width="491" alt="image" src="https://user-images.githubusercontent.com/8086995/192564884-2713f0d9-682c-4e97-b75a-365c09ea1d09.png">

**Comment by JohannesMerkt** [comment]
@petrvecera Ah ok :) No hurry to tackle this atm. If you manage to get ssr to work on the current main branch one thing that would be nice still is the storybook feature. Especially later on when we want to work on components in isolation and test them in different scenarios
