### ISSUE TITLE
Homepage - Create a Reddit card component 

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#10]
Status: Dev Ready

On page https://coh2stats.com/ we have reddit component, which looks like this 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/8086995/195982896-7d38b2a1-02e6-46f9-8b71-4eadeeae9ab6.png">

Taks:
- Recreate this with in COH3
- Use Mantine lib https://mantine.dev/  << check if we can make it pretty by using default features
- The data fetching is created for this.
- You can just implement the component in https://github.com/cohstats/coh3-stats/blob/master/screens/home/reddit-panel/index.tsx
- You can position the component in https://github.com/cohstats/coh3-stats/blob/master/screens/home/index.tsx#L48

You can edit the source data in here https://github.com/cohstats/coh3-stats/blob/master/src/reddit-api.ts

You can re-use the components and source code from version 2:
It's here https://github.com/cohstats/coh2stats/tree/master/packages/web/src/components/reddit

Overall we would like to replicate this website https://aoe4world.com/ so you can look at it as inspiration.

**Comment by Ravina-Deogadkar** [comment]
Hi, can I have a try on this?

**Comment by petrvecera** [comment]
The data fetching is created for this. 
You can just implement the component in https://github.com/cohstats/coh3-stats/blob/master/components/screens/home/reddit-panel/index.tsx
You can position the component in https://github.com/cohstats/coh3-stats/blob/master/components/screens/home/index.tsx#L48

You can edit the source data in here https://github.com/cohstats/coh3-stats/blob/master/src/reddit-api.ts

**Comment by petrvecera** [comment]
DONE
