### ISSUE TITLE
Create image preview component

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#117]
We have images of maps on the recent games. 

I would be great - if you clicked on the image, it would show it in a big version. 

We need to create an universal component for this. It would be great to look if mantine maybe have this? 
Maybe using modal https://mantine.dev/core/modal/? 

![image](https://user-images.githubusercontent.com/8086995/226106217-3a010f82-648d-43b5-87b3-f3ccc61c1277.png)

For example as we have in COH2 https://coh2stats.com/matches/335162384

![image](https://user-images.githubusercontent.com/8086995/226106276-1a1f87db-64f3-48b9-9985-3c1e591c0dad.png)

**Comment by rysllvn** [comment]
I'll look into this.

**Comment by petrvecera** [comment]
epic @rysllvn  nice job 👍
