### ISSUE TITLE
The DPS chart is "flickering" on change

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#133]
When you change something from the dropdowns on the DPS chart https://coh3stats.com/explorer/dps
You can briefly see the footer to jump down. It's CLS - content layout shift. 

I think we need to assign min height to the chart / or the page container.

I wanted to do that, but than I noticed that on the mobile page - it's nicely small, so we might need to add 2 min sizes / mobile and desktop? Something like that. 

@chris-nos  let me know on Discord  if you want look into this

**Comment by chris-nos** [comment]
Found the issue. Had to call a hook to get access to the chart.update instead of calling a redraw property. Will be fixed with the next merge. 

I reduced the containersize so the whole dps tool fits on most screens. Otherwise the user always needs to scroll.

**Comment by chris-nos** [comment]
Accidently added this merged pull request. Have no clue how I can remove this pull request again :D

**Comment by petrvecera** [comment]
Fixed
