### ISSUE TITLE
Player card - Optimize the SSR function

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#145]
On the player card - we have 2 views, one is player card, second one is for matches. 

For example: https://coh3stats.com/players/871
And: https://coh3stats.com/players/871?view=recentMatches

For rendering just the player info we need - jus player info 
For rendering matches, we need player info + recent matches. 

There are 2 ways how to approach player recent matches: 
1. User has link, he goes directly https://coh3stats.com/players/871?view=recentMatches , we need to make 2 request
2. Use is on player profile and than clicks on recentMatches, in this case it would be enough to do just 1 request, to get the data for matches. But we again make 2 requests for both player card and matches. 

**TASK:**
We need to figure out, when you already have player info, don't make the request for player info again. 
The code is here https://github.com/cohstats/coh3-stats/blob/master/pages/players/%5BplayerID%5D.tsx#L172

_Problem:_ We have ~25k player card displayed each day, but requests on the BE are ~50k. It's eating $$

**Comment by komnb14** [comment]
hmm.. i want to make sure that 2 pages (player standing, recent Matches) should not be updated or not get the latest data? or should we get the latest data when we click a correct tab?

if we don't need the latest data everytime, we can just use shallow routing

**Comment by petrvecera** [comment]
It should be in a way - that if we already have player standing data and we
click on matches, the player standing data are not fetch again.

We do have a cache , so when you click on matches and than again on players
it's taken from cache.
