### ISSUE TITLE
clicking on rank from player standings highlights wrong page in the pagination component on the leaderboard page

### ISSUE THREAD

**Issue by rysllvn** [cohstats/coh3-stats#147]
If you navigate to the leader board by clicking on a players rank from their player standings page, the pagination component on the leader board always highlights the first page even if it is on a different page.

**Comment by sanjaykumaryada** [comment]
can you assign this to me

**Comment by rysllvn** [comment]
It looks to be working now actually. Going to just close the issue.

**Comment by petrvecera** [comment]
@sanjaykumaryada  this issues is for grabs https://github.com/cohstats/coh3-stats/issues/257
