### ISSUE TITLE
Create popup on the dev site to use the main site

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#173]
Let's create a modal window / or floating window, which can be located on the left bottom corner. 
This component should appear if people are on the dev.coh3stats.com and it should notify them:
You are using dev version of the site. If you are not here on purpose, please use the main version at https://coh3stats.com

and it should be live link which will take them there. 
You should be able to close the window.

**Comment by rysllvn** [comment]
https://github.com/cohstats/coh3-stats/pull/180
