### ISSUE TITLE
Bug - the dev warning is too big on mobile

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#210]
We have warning in case you visit dev.coh3stats.com that you should not sue that site. 
But the warning is too big on mobile and doesn't fit the screen. 

![image](https://github.com/cohstats/coh3-stats/assets/8086995/b8ac5069-d2a8-49c6-906b-443ba3fc9ebe)

We need to fix that https://github.com/cohstats/coh3-stats/blob/master/components/dev-site-notification.tsx

Maybe limit the width of the dialog with size https://mantine.dev/core/dialog/?t=props

**Comment by apikmeister** [comment]
Hi, I would like to work on this. Can you assign this to me?

**Comment by apikmeister** [comment]
Hi, i've just tested for the warning dialog. It seems fine to me on smaller to extra small screen.
![Screenshot 2023-10-16 at 1 48 10 PM](https://github.com/cohstats/coh3-stats/assets/92358212/71649d20-0ea5-4974-b093-70edd8145c21)

**Comment by petrvecera** [comment]
Hi @apikmeister  it looks like it was a bug in underlaying library which we used. I recently updated it and it probably fixed it. 
If you are interested I am planning a new tasks which can be worked on. I can tag you in case you would like to work on it.

**Comment by apikmeister** [comment]
I would love to, thank you!

**Comment by petrvecera** [comment]
@apikmeister  if you are interested https://github.com/cohstats/coh3-stats/issues/272 or https://github.com/cohstats/coh3-stats/issues/257
