### ISSUE TITLE
Create achievements page & achievement components 

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#272]
Task status: Ready for development 
Difficulty: Medium
------------------------------

We want to create new page including achievements 

We will want to mimick this page https://steamcommunity.com/stats/1677280/achievements/

<img width="969" alt="image" src="https://github.com/cohstats/coh3-stats/assets/8086995/2af5b184-b8e5-49a6-a1ff-9e47c26f8e04">

Development:
1. Data fetching and files are ready for you 
2. Download the repo, run `yarn`, `yarn dev` and open in your browser http://localhost:3000/stats/achievements
3. Open file `screens/stats/achievements/index.tsx` here, you can implement the page
4. There is extra component `screens/stats/achievements/achivement.tsx` which should be the single achievement item
5. You can create any other components you need 

The achievement component should display:
1. Icon
2. Title
3. Description 
4. Progress in terms of % 

Preferably utilising components from this library https://mantine.dev/core
For example we could utilize progress component for the progress bar https://mantine.dev/core/progress/#compound-components
Each achievement could be card https://mantine.dev/core/card/ 
But it's up to you how you want to stylise the components

Achievements should be sorted by the most %

**Comment by apikmeister** [comment]
Hi, I would love to work on this! Can you assign me?

**Comment by petrvecera** [comment]
Thank you ❤️
