### ISSUE TITLE
Improve about page

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#29]
About page should be on url /about

It should be one page with sections for more things - similar what we have on https://coh2stats.com/about

But it should have table of contents on the side, similar what is here https://aoe4world.com/faq#leaderboard

The content of the page can be populated later

**Comment by petrvecera** [comment]
We still need to clean up the about page and add table of contents there

**Comment by MarkTallentire** [comment]
Hi @petrvecera. 

I should be able to start work on this today. Just dropping a note in case anyone else is working on it.

Mark

**Comment by petrvecera** [comment]
Hi @MarkTallentire, awesome. 

Basically this task is just about making that menu, which would scroll you on that page. 
Everything for the about page is here https://github.com/cohstats/coh3-stats/blob/master/pages/about.tsx

Let me know if you have any questions :)
