### ISSUE TITLE
Add unit stats

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#34]
The source data for this should be JSON, it should be separated by PATH. So you can select a patch version from a drop down. 

Create those jsons in /src/coh3/data ...
Create a folder in /pages/units/...

It's up to you how to to code those units 

Inspiration for good design can be taken from here https://aoe4world.com/explorer/civs/english/units/trader

**Comment by rempAut** [comment]
We need to finish our work [here ](https://github.com/cohstats/coh3-data)

Currently Munuk and me are collecting a list of interesting datapoints and we need a script to export the unit stats to JSON(s)

So far there is this template file, of what we would like to have.
https://github.com/cohstats/coh3-data/blob/MuNuk/todo/infantry_todo.md

**Comment by chris-nos** [comment]
Working on the dps calculation. For an awesome user experience I'm targeting a dynamic DPS calculation where users are able to customize their squads: Adding/removing models, weapons upgrades, veterancy, cover etc.  An hierarichal json structure like this draft would be great for that. 
[coh3_stats_draft.txt](https://github.com/cohstats/coh3-stats/files/10838974/coh3_stats_draft.txt)

**Comment by KingDarBoja** [comment]
Working on the UI Cards so we can have some sort of example unit page then re-arrange the styling and input data when it is ready. :)

**Comment by petrvecera** [comment]
Done 👍
