### ISSUE TITLE
Playercard not working for certain players

### ISSUE THREAD

**Issue by Tobie-08** [cohstats/coh3-stats#41]
Seems if you have a 3 number relic ID, then it can't find your playercard. Examples:

Rei - https://dev.coh3stats.com/players/871
Sturmpanther - https://dev.coh3stats.com/players/816
Nyx - https://dev.coh3stats.com/players/319

**Comment by petrvecera** [comment]
This is an issue on relic side. I will reach out to them.

**Comment by petrvecera** [comment]
Fixed
