### ISSUE TITLE
Incorrect position when you visit a NEWs article with a link

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#419]
When you visit a news article with a link, for example like this
https://coh3stats.com/news#5749481331455590646

It scrolls the page little bit below the header
The code for this is here https://github.com/cohstats/coh3-stats/blob/master/screens/news/index.tsx#L127

<img width="1056" alt="image" src="https://github.com/cohstats/coh3-stats/assets/8086995/93868463-47ec-42c6-99f5-a94d360ec159">

**Comment by jeevikasirwani** [comment]
maybe adding margin to container
