### ISSUE TITLE
Filters and sorting recent matches tab

### ISSUE THREAD

**Issue by rysllvn** [cohstats/coh3-stats#55]
There are only 10 matches per match type, but it still might be nice to be able to filter the recent matches tab (by game sized, faction, win/lose, etc.). What do you think? I was thinking filtering `<Select />`. Also could make the column headers clickable for sorting.

I was thinking this might be a good first feature/issue for myself. I've used react plenty, but would be getting used to mantine and next. I don't think there would be much to this that is next specific since all of the data is already fetched for this tab.

**Comment by petrvecera** [comment]
@rysllvn  yes, we can definitely add this, we are using this table https://icflorescu.github.io/mantine-datatable/

You can setup sorting https://icflorescu.github.io/mantine-datatable/examples/sorting

Not sure about the filtering. It would be great if we could do it as we have in coh2stats.com
https://coh2stats.com/players/76561198051168720-F3riG?view=recentMatches

But I am not sure if that libary supports something for nice filtering

**Comment by petrvecera** [comment]
It looks like you can do a custom column header like this:
```
  title: (
            <Center>
              <ArrowsUpDown size={14} />
            </Center>
          ),
```

Maybe we could put this into the title https://mantine.dev/core/select/  , you can try, if you are stuck let me know 👍

**Comment by rysllvn** [comment]
Thanks. I'll take a look at the coh2stats one and try and see how close I can get it to that.

**Comment by petrvecera** [comment]
Btw if it's too hard to put it into the column header we can also put it above the table. 👍

**Comment by rysllvn** [comment]
I'm not sure if it's hard to add an icon into a mantine table header. I didn't try yet. Was just trying sorting yesterday.

**Comment by rysllvn** [comment]
btw, working on the filters. Should be able to make it just like in coh2 stats which I think works well.

**Comment by rysllvn** [comment]
These are both merged now. I'll close this. There is a bug, but another issue already created. [#94](https://github.com/cohstats/coh3-stats/issues/94#issue-1617989517).
