### ISSUE TITLE
About - Menu not sticking

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#557]
On the about page https://coh3stats.com/about we have a menu. This menu should stick top the top when you scroll down. (aka it should be always visible) 

The code is defined here, the div should stick 
https://github.com/cohstats/coh3-stats/blob/master/screens/about/index.tsx#L254

Feel free to ask any questions. 

![image](https://github.com/user-attachments/assets/89d61aec-eb76-4739-bfa8-f414d16085a8)

![image](https://github.com/user-attachments/assets/1186dc7b-827b-4e76-ab3d-f0f9779e8f24)

**Comment by petrvecera** [comment]
@RajVerma97  you crushed all the open tickets here 🤯 
Would you be interested in some bigger tasks? I could prepare some more challenging pieces of code

**Comment by RajVerma97** [comment]
yeah sure

**Comment by petrvecera** [comment]
I will prepare somethnig
