### ISSUE TITLE
debouncedQuery is not reset when to close spotlight

### ISSUE THREAD

**Issue by komnb14** [cohstats/coh3-stats#57]
![image](https://user-images.githubusercontent.com/83199839/222742485-5d30d842-c5fe-49b6-acbe-4cf5e824a4b7.png)

i don't know it's intended or not. seems like you guys forget to reset spotlight value.

just add 

onSpotlightClose={() => setDebouncedQuery("")} 

will fix this problem

**Comment by petrvecera** [comment]
Thanks, feel free to make PR if you can 👍 

We will need to re-write the search in future, this is the first version to make it work ASAP.

**Comment by komnb14** [comment]
merged
