### ISSUE TITLE
Polish the mobile view for Youtube Cards

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#587]
Problem: On the home screen we have YouTube cards. They are working nice. But when you open the view on the phone. The cards are too big. https://coh3stats.com/

We want the cards to be smaller on the mobile view, so we can fit 2 of them next to each other. But they should stay the same on desktop view.

Code:
https://github.com/cohstats/coh3-stats/tree/master/screens/home/youtube-panel

You can add any css here
https://github.com/cohstats/coh3-stats/blob/master/screens/home/youtube-panel/youtube-panel.module.css

You can use media queries in the CSS 
https://mantine.dev/styles/responsive/

![image](https://github.com/user-attachments/assets/dd7d7d91-c08d-4f70-a2c9-c490c8a31a37)
![image](https://github.com/user-attachments/assets/171c32c9-beeb-479a-8716-3f04d8ceff59)

**Comment by petrvecera** [comment]
@RajVerma97 I noticed on your screenshots, that it doesn't load for you some of the data / can you share your logs - both from browser and from the running dev server - terminal? Do you run the dev server with `yarn dev` ? You can also try `yarn next`

**Comment by RajVerma97** [comment]
i did yarn next this time ,still same issue no youtube videos

### Browser
<img width="1280" alt="Screenshot 2024-10-01 at 6 03 03 PM" src="https://github.com/user-attachments/assets/56d2dbd3-f23e-42e4-8579-283ccd9947b6">

###Server

<img width="1280" alt="Screenshot 2024-10-01 at 6 03 16 PM" src="https://github.com/user-attachments/assets/93efc869-1028-4559-81d3-b8caeae0b1fb">

**Comment by petrvecera** [comment]
@RajVerma97 The issue in browser is fine. The problem is in the server / node JS. It looks like you have a problem with node installation and it has a problem with TSL certificates. It's connecting to various public services. I assume this link https://api.steampowered.com/ISteamUserStats/GetNumberOfCurrentPlayers/v1/?appid=1677280 works for you in the browser? 

You can try this in terminal - run `node` and then paste this command `await (await fetch("https://api.steampowered.com/ISteamUserStats/GetNumberOfCurrentPlayers/v1/?appid=1677280")).text()` I think you will get the same issue? 

I would probably try:
- check that macos is updated 
- restart the system 
- reinstall the nodejs ( I recommend using NVM https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating in case you are not using any other manager)

**Comment by RajVerma97** [comment]
it worked after my disconnected my LAN and used my phone's Hotspot to open build locally .
Thanks a lot.
I will now start working on this issue😯
