### ISSUE TITLE
Match details page - table

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#605]
This is subtask of https://github.com/cohstats/coh3-stats/issues/606

Create a table similar to https://coh2stats.com/matches/376329140

![image](https://github.com/user-attachments/assets/abe4ed98-4ea6-4898-97cb-160b563f0833)

First you will need to split the players into two teams, you can do so with this function 
https://github.com/cohstats/coh3-stats/blob/master/screens/players/tabs/recent-matches-tab/player-recent-matches-tab.tsx#L302

For the tables, we are using mantine databale https://github.com/cohstats/coh3-stats/blob/master/screens/players/tabs/recent-matches-tab/player-recent-matches-tab.tsx#L176
docs can be found here https://icflorescu.github.io/mantine-datatable/

The data for the table, they are on the match object under `matchhistoryreportresults` under key 
`counters`. 

The counters are described in this post https://github.com/cohstats/coh3-stats/issues/194#issuecomment-1520530220

The stuff we want to display in the table:
- Damage done - dmgdone
- Units killed - ekills
- Units lossed - edeaths
- K/D -  ekills / edeaths 
- Squads Killed - sqkilled
- Squads Made  - sqprod
- Squads Lost  - sqlost
- Vehicles Killed - vkill
- Vehicles prod - vprod
- Vehicles Lost - vlost
- Points catupre - pcap
- Poinst lost - plost
- Points recaptured - precap
- Total Commands - totalcmds 
- Abilities Used - abil

^^ we might need to edit this later / add or remove, but in the first version we can just show this 

Example counters
```
{\"abil\":49,\"addonkill\":36,\"blost\":2,\"bprod\":11,\"cabil\":6,\"cflags\":0,\"cpearn\":3,\"dmgdone\":4612,\"edeaths\":60,\"ekills\":42,\"elitekill\":3,\"erein\":24,\"gammaspnt\":0,\"gt\":1062,\"inactperiod\":22,\"lowintperiod\":0,\"objdmh\":0,\"pcap\":8,\"plost\":3,\"popmax\":0,\"powearn\":0,\"powmax\":0,\"powspnt\":0,\"precap\":6,\"reqearn\":0,\"reqmax\":0,\"reqspnt\":0,\"sqkill\":7,\"sqlost\":9,\"sqprod\":8,\"structdmg\":8,\"svetrank\":1,\"svetxp\":1200,\"totalcmds\":1030,\"unitprod\":36,\"upg\":44,\"vabnd\":0,\"vcap\":0,\"vkill\":3,\"vlost\":0,\"vp0\":0,\"vp1\":0,\"vprod\":1,\"vvetrank\":11,\"vvetxp\":18150,\"wpnpu\":12}",
```

**Comment by RajVerma97** [comment]
### As of right now I have just put some dummy data for commanders and bulletins.  How am i going to  the data of commanders and bulletins for each player . Is there already an api endpoint for that?

<img width="1280" alt="Screenshot 2024-10-08 at 3 05 40 AM" src="https://github.com/user-attachments/assets/b2587044-cb05-4384-a113-7e5c7c49bbbe">




<img width="1280" alt="Screenshot 2024-10-08 at 3 08 05 AM" src="https://github.com/user-attachments/assets/b47fe6c9-0ab6-4194-be7b-813925d9fc65">

**Comment by petrvecera** [comment]
Hi, sorry about that, please don't worry about that / don't add it there. I still don't have the code analyzed / don't know the IDs of the commanders. 

Btw for the colors in the table - except for the green / red in the background. I think you can utilize the default ones from the table. So no need to make the header white. That way it should work automatically when you switch the color them of the application. ( top right corner button). 

Btw feel free to make a PR if you want to get any hints in the code.
