### ISSUE TITLE
Create match details page 

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#606]
We want to create a single match details page.  This task is divided into subtasks. 

This match details page will include:
- Header displaying global match information  https://github.com/cohstats/coh3-stats/issues/604
- Table of team 1 and team 2 https://github.com/cohstats/coh3-stats/issues/605
- Summary charts <TBD>

The example page is available on this url:
`/matches/31226243?profileIDs=[102119,%204566,%2057433,%20322047,%20138403,%20427875,%2058386,%20887819]`
aka https://dev.coh3stats.com/matches/31226243?profileIDs=[102119,%204566,%2057433,%20322047,%20138403,%20427875,%2058386,%20887819]
 
The content lives in this file 
https://github.com/cohstats/coh3-stats/blob/master/screens/matches/match-detail.tsx

The page should look similarly as it looks on coh2stats
https://coh2stats.com/matches/376351317

![image](https://github.com/user-attachments/assets/da6f099b-38fd-4850-bb07-8024b06958a7)

**Comment by RajVerma97** [comment]
got it ! Thanks for the explanation and guidance!
I will give it a shot!

**Comment by RajVerma97** [comment]
Is there already a component table like this or do i have to create one ?

<img width="1246" alt="Screenshot 2024-10-07 at 12 29 12 AM" src="https://github.com/user-attachments/assets/47744ef6-1f37-4113-a5dd-1cbb40cec4a7">

**Comment by petrvecera** [comment]
> Is there already a component table like this or do i have to create one ?
> 
> <img alt="Screenshot 2024-10-07 at 12 29 12 AM" width="1246" src="https://private-user-images.githubusercontent.com/61057997/373973033-47744ef6-1f37-4113-a5dd-1cbb40cec4a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDIzNTAsIm5iZiI6MTcyODI0MjA1MCwicGF0aCI6Ii82MTA1Nzk5Ny8zNzM5NzMwMzMtNDc3NDRlZjYtMWYzNy00MTEzLWE1ZGQtMWNiYjQwY2VjNGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE5MTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZjExMmE4NGI3ZTNlZDI1NzdmODY4NzNhOGFlNTRlNjI3YWYwMTAzY2Y4N2U4ZWZhZWFjNzQyZTE3ZGQxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NabcAaJDVolk_Brz9jhHlMaev9R7pA4x_y9EcV9ZwKA">

In coh3stats we don't have table like this. You will need to create a new one. The best inspiration can be taken on the matches table https://github.com/cohstats/coh3-stats/blob/master/screens/players/tabs/recent-matches-tab/player-recent-matches-tab.tsx#L176

**Comment by RajVerma97** [comment]
what about charts?  like DAMAGE DEALT ,UNITS KILLED?

**Comment by petrvecera** [comment]
> what about charts? like DAMAGE DEALT ,UNITS KILLED?

I will explain the charts in the separate sub-issue later, but no - all charts are hand crafted for the specific visualisation.

**Comment by RajVerma97** [comment]
okay got it 
i sent a dm to you on discord. My username is Rajneesh Verma
