### ISSUE TITLE
Player search is broken

### ISSUE THREAD

**Issue by allgoewer** [cohstats/coh3-stats#670]
Player search seems to be broken right now.

See the following link for an example: https://coh3stats.com/search?q=tightrope

![Screenshot_20241204-130700](https://github.com/user-attachments/assets/1a8f05d1-5227-4a5c-ae4d-4727e9040e3d)

**Comment by petrvecera** [comment]
Thank you for the report, the issues should be fixed, please let me know otherwise 🙏

**Comment by allgoewer** [comment]
Something still seems to be broken.

My profile exists:

[/dev/null](https://coh3stats.com/players/63411/devnull)

Searching for `/dev/null` gives no results.

**Comment by petrvecera** [comment]
@allgoewer  thanks for the report, there was bug with special characters like `/` should be fixed
