### ISSUE TITLE
recent matches played ago format

### ISSUE THREAD

**Issue by timhubert** [cohstats/coh3-stats#75]
If the match was not even an hour ago, it is nicer to display the minutes ago.
1h < time < 10h should display hours without 0 in front.

Timeago.js package is already installed and I changed `formatMatchTime` (marked as old) function from utils.ts to timeage.js,

![grafik](https://user-images.githubusercontent.com/7204823/222936376-96f5739c-3e1f-4ec1-b527-b10b203179cf.png)

**Comment by petrvecera** [comment]
Thanks 👍
