### ISSUE TITLE
Mantine Datatable unique key prop error

### ISSUE THREAD

**Issue by JohannesMerkt** [cohstats/coh3-stats#83]
Probably not an important fix, but every occurence (leaderboard / playercard) of the mantine datatable currently causes this error:
![grafik](https://user-images.githubusercontent.com/25324640/223148893-916fd7a0-9207-4839-8e72-4f4106cabd91.png)

Couldn't figure out why but it seems to be inside the render function of the column prop
![grafik](https://user-images.githubusercontent.com/25324640/223149209-8f86b5b9-5730-4d4e-b08c-08a51eafd379.png)

this is the only issue I found about this:
https://github.com/icflorescu/mantine-datatable/issues/182
it seems to be our fault

**Comment by petrvecera** [comment]
I looked at the code and can't figure out where we have it wrong ? ...

**Comment by komnb14** [comment]
Datatable's default key is id. simply set idAccessor will fix this bug
