### ISSUE TITLE
Searching users with curly brackets {} characters in name does not work

### ISSUE THREAD

**Issue by mkosmala1984** [cohstats/coh3-stats#91]
Example profile that is not searchable https://coh3stats.com/players/4440

**Comment by petrvecera** [comment]
Hi

There is more issues with search. Currently we rely on Relic search and
their search is limited. We will implement other approach in future.

**Comment by petrvecera** [comment]
We just released a fix for this. The search should now work for special characters too https://coh3stats.com/search?q=%5BPAX
