### ISSUE TITLE
Filter on the table is not visible when there are no data

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#94]
When you try to filter table and you remove all the data the filter is hidden. 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/8086995/224156584-1e7aee13-c47c-4ac7-a0ed-9584eb1cab99.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/8086995/224156709-54d4c633-b4e3-4e87-9b98-01b6b8d1b8b7.png">

We need to get the poover over the table somehow. I tried to play with the z-index but it didn't help on the popover. Maybe we need to apply it somewhere else?

**Comment by rysllvn** [comment]
Okay interesting. I'll take a look later today.

**Comment by komnb14** [comment]
three dom node has overflow: 'hidden' or 'scroll'

![image](https://user-images.githubusercontent.com/83199839/224347152-dc25f978-3468-4925-a744-ad3697f8f159.png)
![image](https://user-images.githubusercontent.com/83199839/224347206-532ee315-8da4-4401-945e-5e379a9895b6.png)
![image](https://user-images.githubusercontent.com/83199839/224347249-ed0be0b7-1322-4c6d-8737-01a3c3240b88.png)

and i think Mantine DataTable is not actually support for overflow handling

**Comment by petrvecera** [comment]
Yeah I think it's some fuckup from the mantine datatable. Awesome findings.  Would we be able to fix this with our styles which we could put on the table?

**Comment by komnb14** [comment]
if we just turn off overflow, mobile layout is broke. :(

![image](https://user-images.githubusercontent.com/83199839/224355049-477d745e-9e4b-4d2b-ada6-f5bc55b0eda1.png)

**Comment by rysllvn** [comment]
@petrvecera montag, I'm on the server

**Comment by petrvecera** [comment]
@komnb14  fix it 👍  thanks a lot ❤️
